### ISSUE TITLE
Issue on Deploying Resources

### ISSUE THREAD

**Issue by jccastellanos144** [OfficeDev/microsoft-teams-apps-growyourskills#20]
There is an error deploying the source controls when using the recommended template.

It seems to be in this line. I don´t know if it is about the Branch access or name.
"resources": [
                {
                    "type": "sourcecontrols",
                    "apiVersion": "2016-08-01",
                    "name": "web",
                    "dependsOn": [
                        "[resourceId('Microsoft.Web/sites', variables('botAppName'))]"
                    ],
                    "properties": {
                        "RepoUrl": "[parameters('gitRepoUrl')]",
                        "branch": "[parameters('gitBranch')]",
                        "IsManualIntegration": true
                    },
                    "condition": "[not(empty(parameters('gitRepoUrl')))]"
                }
            ]

![SourceControl](https://user-images.githubusercontent.com/40745731/117900580-1823d100-b28f-11eb-9255-86cc2cfcb8f5.png)

**Comment by v-smahaj** [comment]
Thanks for reporting this.
Can you try upgrading App Service plan to S2 or S3 and try again.
Let us know if issue still persists.
